services:
    ens.jobeet.admin.category:
        class: Ens\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments:
            - ~
            - Ens\JobeetBundle\Entity\Category
            - 'EnsJobeetBundle:CategoryAdmin'

    ens.jobeet.admin.job:
        class: Ens\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments:
            - ~
            - Ens\JobeetBundle\Entity\Job
            - 'EnsJobeetBundle:JobAdmin'
    ens.jobeet.admin.affiliate:
        class: Ens\JobeetBundle\Admin\AffiliateAdmin
        tags:
        - { name: sonata.admin, manager_type: orm, group: jobeet, label: Affiliates }
        arguments:
        - ~
        - Ens\JobeetBundle\Entity\Affiliate
        - 'EnsJobeetBundle:AffiliateAdmin'